import Audio from "@/models/audio";
import AutoGeneratedPlaylist from "@/models/autoGeneratedPlaylist";
import cron from "node-cron";

// The five fields in the cron syntax represent:
// - Second (optional)
// - Minute
// - Hour
// - Day of the month
// - Month
// - Day of the week (optional)

// cron.schedule("*/2 * * * * *", () => {
//     console.log("Running scheduled task");
// })

const generatePlaylist = async () => {
  const result = await Audio.aggregate([
    {
      $sort: { likes: -1 },
    },
    {
      $sample: { size: 20 },
    },
    {
      $group: {
        _id: "$category",
        audios: { $push: "$_id" },
      },
    },
  ]);

  result.map(async (item) => {
    await AutoGeneratedPlaylist.updateOne(
      { title: item._id },
      { $set: { items: item.audios } },
      { upsert: true }
    );
  });
};

cron.schedule("0 0 * * *", async () => {
  // this will run at every 24hr
  await generatePlaylist();
});
