import { RequestHandler } from "express";
import mongoose, { isValidObjectId, PipelineStage } from "mongoose";
import User from "@/models/user";
import { paginationQuery } from "@/@types/misc";
import Audio, { AudioDocument } from "@/models/audio";
import Playlist from "@/models/playlist";
import History from "@/models/history";
import moment from "moment";
import AutoGeneratedPlaylist from "@/models/autoGeneratedPlaylist";
import { getUsersPreviousHistory } from "@/utils/helper";
import { Types } from "mongoose";

export const updateFollower: RequestHandler = async (req, res) => {
  const { profileId } = req.params;
  const userId = req.user.id;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ message: "Invalid profile ID" });

  if (profileId === userId)
    return res.status(400).json({ message: "You cannot follow yourself" });

  const profile = await User.findById(profileId);
  if (!profile) return res.status(404).json({ message: "Profile not found" });

  const alreadyFollower = profile.followers.includes(userId);
  const status: "added" | "removed" = alreadyFollower ? "removed" : "added";

  if (alreadyFollower) {
    await User.updateOne({ _id: profileId }, { $pull: { followers: userId } });
    await User.updateOne({ _id: userId }, { $pull: { followings: profileId } });
  } else {
    await User.updateOne(
      { _id: profileId },
      { $addToSet: { followers: userId } },
    );
    await User.updateOne(
      { _id: userId },
      { $addToSet: { followings: profileId } },
    );
  }

  return res.json({ message: "Follower updated successfully", status });
};

export const getUploads: RequestHandler = async (req, res) => {
  const { pageNo = "0", limit = "20" } = req.query as paginationQuery;

  const data = await Audio.find({ owner: req.user.id })
    .skip(parseInt(pageNo) * parseInt(limit))
    .limit(parseInt(limit))
    .sort({ createdAt: -1 });

  const audios = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      about: item.about,
      file: item.file.url,
      category: item.category,
      poster: item.poster?.url,
      date: item.createdAt,
      owner: { name: req.user.name, id: req.user.id },
    };
  });

  res.status(201).json({ audios });
};

export const getPublicUploads: RequestHandler = async (req, res) => {
  const { pageNo = "0", limit = "20" } = req.query as paginationQuery;
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ message: "Invalid profile ID" });

  const data = await Audio.find({ owner: profileId })
    .skip(parseInt(pageNo) * parseInt(limit))
    .limit(parseInt(limit))
    .sort({ createdAt: -1 })
    .populate<AudioDocument<{ name: string; _id: mongoose.Types.ObjectId }>>(
      "owner",
    );

  const audios = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      about: item.about,
      file: item.file.url,
      poster: item.poster?.url,
      date: item.createdAt,
      owner: { name: item.owner.name, id: item.owner._id },
    };
  });

  res.status(201).json({ audios });
};

export const getPublicProfile: RequestHandler = async (req, res) => {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile ID" });

  const profile = await User.findById(profileId);

  if (!profile) return res.status(404).json({ error: "Profile not found" });

  res.status(200).json({
    profile: {
      id: profile._id,
      name: profile.name,
      followers: profile.followers.length,
      avatar: profile.avatar?.url,
    },
  });
};

export const getPublicPlaylist: RequestHandler = async (req, res) => {
  const { profileId } = req.params;
  const { limit = "20", pageNo = "0" } = req.query as paginationQuery;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile ID" });

  const data = await Playlist.find({ owner: profileId, visibility: "public" })
    .skip(parseInt(pageNo) * parseInt(limit))
    .limit(parseInt(limit))
    .sort({ createdAt: -1 });

  if (!data) return res.status(404).json({ error: "Playlists not found" });

  const playlists = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      itemsCount: item.items.length,
      visibility: item.visibility,
    };
  });

  res.status(201).json({ playlists });
};

export const getRecommendByProfile: RequestHandler = async (req, res) => {
  const user = req.user;

  let matchOptions: PipelineStage.Match = {
    $match: { _id: { $exists: true } },
  };

  if (user) {
    const categories = await getUsersPreviousHistory(req);

    if (categories.length > 0) {
      matchOptions = { $match: { category: { $in: categories } } };
    }
  }

  // otherwise we will send generic audios
  const audios = await Audio.aggregate([
    matchOptions,
    {
      $sort: {
        "likes.count": -1,
      },
    },
    { $limit: 10 },
    {
      $lookup: {
        from: "users",
        localField: "owner",
        foreignField: "_id",
        as: "owner",
      },
    },
    { $unwind: "$owner" },
    {
      $project: {
        _id: 0,
        id: "$_id",
        title: "$title",
        category: "$category",
        about: "$about",
        file: "$file.url",
        poster: "$poster.url",
        owner: { name: "$owner.name", id: "$owner._id" },
      },
    },
  ]);

  res.json({ audios });
};

export const getAutoGeneratedPlaylist: RequestHandler = async (req, res) => {
  // 1️⃣ Create Mix 20 playlist from last 20 audios
  const [result] = await History.aggregate([
    { $match: { owner: new Types.ObjectId(req.user.id) } },
    { $unwind: "$all" },
    { $group: { _id: "$all.audio", items: { $addToSet: "$all.audio" } } },
    { $sample: { size: 20 } },
    { $group: { _id: null, items: { $push: "$_id" } } },
  ]);

  const mixTitle = "Mix 20";

  if (result) {
    await Playlist.updateOne(
      { owner: req.user.id, title: mixTitle },
      { $set: { title: mixTitle, items: result.items, visibility: "auto" } },
      { upsert: true },
    );
  }

  // 2️⃣ Fetch user’s recently listened categories
  const categories = await getUsersPreviousHistory(req);

  // 3️⃣ Fetch 4 random AutoGeneratedPlaylists (ignore categories for now)
  const agpl = await AutoGeneratedPlaylist.aggregate([
    { $sample: { size: 4 } },
    {
      $project: {
        _id: 0,
        id: "$_id",
        title: "$title",
        itemsCount: { $size: "$items" },
      },
    },
  ]);

  // 4️⃣ Fetch Mix 20 playlist document
  const mixPlaylist = await Playlist.findOne({
    owner: req.user.id,
    title: mixTitle,
  });

  // 5️⃣ Combine auto playlists + Mix 20
  const finalList = [
    ...agpl,
    {
      id: mixPlaylist?._id,
      title: mixPlaylist?.title,
      itemsCount: mixPlaylist?.items.length ?? 0,
    },
  ];

  res.json({ playlist: finalList });
};

export const getFollowersProfile: RequestHandler = async (req, res) => {
  const { pageNo = "0", limit = "20" } = req.query as paginationQuery;

  const [data] = await User.aggregate([
    { $match: { _id: new Types.ObjectId(req.user.id) } },
    {
      $project: {
        followers: {
          $slice: [
            "$followers",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    {
      $unwind: "$followers",
    },
    {
      $lookup: {
        from: "users",
        localField: "followers",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    {
      $unwind: "$userInfo",
    },
    {
      $group: {
        _id: null,
        followers: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar?.url",
          },
        },
      },
    },
  ]);

  if (!data) return res.status(404).json({ followers: [] });

  res.status(201).json({ followers: data.followers });
};

export const getFollowingsProfile: RequestHandler = async (req, res) => {
  const { pageNo = "0", limit = "20" } = req.query as paginationQuery;

  const [data] = await User.aggregate([
    { $match: { _id: new Types.ObjectId(req.user.id) } },
    {
      $project: {
        followings: {
          $slice: [
            "$followings",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    {
      $unwind: "$followings",
    },
    {
      $lookup: {
        from: "users",
        localField: "followings",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    {
      $unwind: "$userInfo",
    },
    {
      $group: {
        _id: null,
        followings: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar?.url",
          },
        },
      },
    },
  ]);

  if (!data) return res.status(404).json({ followings: [] });

  res.status(201).json({ followings: data.followings });
};

export const getFollowersProfilePublic: RequestHandler = async (req, res) => {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile ID" });

  const { pageNo = "0", limit = "20" } = req.query as paginationQuery;

  const [data] = await User.aggregate([
    { $match: { _id: new Types.ObjectId(profileId) } },
    {
      $project: {
        followers: {
          $slice: [
            "$followers",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    {
      $unwind: "$followers",
    },
    {
      $lookup: {
        from: "users",
        localField: "followers",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    {
      $unwind: "$userInfo",
    },
    {
      $group: {
        _id: null,
        followers: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar?.url",
          },
        },
      },
    },
  ]);

  if (!data) return res.status(404).json({ followers: [] });

  res.status(201).json({ followers: data.followers });
};

export const getPlaylistAudios: RequestHandler = async (req, res) => {
  const { playlistId } = req.params;
  const { pageNo = "0", limit = "20" } = req.query as paginationQuery;

  if (!isValidObjectId(playlistId))
    return res.status(422).json({ error: "Invalid playlist ID" });

  const aggregationLogic = [
    {
      $match: {
        _id: new Types.ObjectId(playlistId),
        $or: [
          { visibility: { $exists: false } },
          { visibility: { $ne: "private" } },
        ],
      },
    },
    {
      $project: {
        items: {
          $slice: [
            "$items",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
        title: "$title",
        owner: "$owner",
      },
    },
    {
      $unwind: "$items",
    },
    {
      $lookup: {
        from: "audios",
        localField: "items",
        foreignField: "_id",
        as: "audioInfo",
      },
    },
    {
      $unwind: "$audioInfo",
    },
    {
      $lookup: {
        from: "users",
        localField: "owner",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    {
      $unwind: "$userInfo",
    },
    {
      $group: {
        _id: {
          id: "$_id",
          title: "$title",
        },
        audios: {
          $push: {
            id: "$audioInfo._id",
            title: "$audioInfo.title",
            about: "$audioInfo.about",
            category: "$audioInfo.category",
            file: "$audioInfo.file.url",
            poster: { $ifNull: ["$audioInfo.poster.url", null] },
            owner: { name: "$userInfo.name", id: "$userInfo._id" },
          },
        },
      },
    },
    {
      $project: {
        _id: 0,
        id: "$_id.id",
        title: "$_id.title",
        audios: "$$ROOT.audios",
      },
    },
  ];

  const [playlistResult] = await Playlist.aggregate(aggregationLogic);

  if (playlistResult) {
    return res.status(200).json({ list: playlistResult });
  }

  const [autoPlaylistResult] =
    await AutoGeneratedPlaylist.aggregate(aggregationLogic);

  if (autoPlaylistResult) {
    return res.status(200).json({ list: autoPlaylistResult });
  }

  return res.status(404).json({ error: "Playlist not found" });
};

export const getPrivatePlaylistAudios: RequestHandler = async (req, res) => {
  const { playlistId } = req.params;
  const { pageNo = "0", limit = "20" } = req.query as paginationQuery;

  if (!isValidObjectId(playlistId))
    return res.status(422).json({ error: "Invalid playlist ID" });

  const aggregationLogic = [
    {
      $match: {
        _id: new Types.ObjectId(playlistId),
        owner: new Types.ObjectId(req.user.id),
      },
    },
    {
      $project: {
        items: {
          $slice: [
            "$items",
            parseInt(pageNo) * parseInt(limit),
            parseInt(limit),
          ],
        },
        title: "$title",
        owner: "$owner",
      },
    },
    {
      $unwind: "$items",
    },
    {
      $lookup: {
        from: "audios",
        localField: "items",
        foreignField: "_id",
        as: "audioInfo",
      },
    },
    {
      $unwind: "$audioInfo",
    },
    {
      $lookup: {
        from: "users",
        localField: "owner",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    {
      $unwind: "$userInfo",
    },
    {
      $group: {
        _id: {
          id: "$_id",
          title: "$title",
        },
        audios: {
          $push: {
            id: "$audioInfo._id",
            title: "$audioInfo.title",
            about: "$audioInfo.about",
            category: "$audioInfo.category",
            file: "$audioInfo.file.url",
            poster: "$audioInfo.poster?.url",
            owner: { name: "$userInfo.name", id: "$userInfo._id" },
          },
        },
      },
    },
    {
      $project: {
        _id: 0,
        id: "$_id.id",
        title: "$_id.title",
        audios: "$$ROOT.audios",
      },
    },
  ];

  const [playlistResult] = await Playlist.aggregate(aggregationLogic);

  if (!playlistResult) {
    const [autoPlaylistResult] =
      await AutoGeneratedPlaylist.aggregate(aggregationLogic);
    return res.status(201).json({ list: autoPlaylistResult });
  }

  res.status(201).json({ list: playlistResult });
};

export const getIsFollowing: RequestHandler = async (req, res) => {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile ID" });

  const isFollowing = await User.findOne({
    _id: new Types.ObjectId(profileId),
    followers: new Types.ObjectId(req.user.id),
  });

  res.status(201).json({ status: isFollowing ? true : false });
};
