import { Types, Schema, model, models, Model } from "mongoose";

interface AutoGeneratedPlaylistDocument extends Document {
  title: string;
  items: Types.ObjectId[];
}

const autoGeneratedPlaylistSchema = new Schema<AutoGeneratedPlaylistDocument>(
  {
    title: {
      type: String,
      required: true,
    },
    items: {
      type: [Schema.Types.ObjectId],
      required: true,
      ref: "Audio",
    },
  },
  {
    timestamps: true,
  }
);

const AutoGeneratedPlaylist = models.AutoGeneratedPlaylist || model("AutoGeneratedPlaylist", autoGeneratedPlaylistSchema);

export default AutoGeneratedPlaylist as Model<AutoGeneratedPlaylistDocument>;