import { isAuth, mustAuth } from "@/middleware/auth";
import express from "express";
import {
  updateFollower,
  getUploads,
  getPublicUploads,
  getPublicProfile,
  getPublicPlaylist,
  getRecommendByProfile,
  getAutoGeneratedPlaylist,
  getFollowersProfile,
  getFollowingsProfile,
  getFollowersProfilePublic,
} from "@/controllers/profile";

const router = express.Router();

router.post("/update-follower/:profileId", mustAuth, updateFollower);

router.get("/uploads", mustAuth, getUploads);

router.get("/uploads/:profileId", getPublicUploads);

router.get("/info/:profileId", getPublicProfile);

router.get("/playlist/:profileId", getPublicPlaylist);

router.get("/recommended", isAuth, getRecommendByProfile)

router.get("/auto-generated-playlist", mustAuth, getAutoGeneratedPlaylist)

router.get("/followers", mustAuth, getFollowersProfile)

router.get("/followings", mustAuth, getFollowingsProfile)

router.get("/followers/:profileId", mustAuth, getFollowersProfilePublic)

export default router;
